version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=remitly
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  

  springboot-app-dp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/remitly
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db

volumes:
  mysql-data:
